core-project-uri: ${SERVICE_SCHEME}://${CORE_PROJECT_HOST}:${CORE_PROJECT_PORT}
core-contractor-uri: ${SERVICE_SCHEME}://${CORE_CONTRACTOR_HOST}:${CORE_CONTRACTOR_PORT}

server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: slate-mcp
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVER}/oauth2/jwks
          issuer-uri: ${AUTH_SERVER}
  ai:
    mcp:
      server:
        name: webmvc-mcp-server
        version: 1.0.0
        type: SYNC  # Recommended for reactive applications
        sse-message-endpoint: /mcp/messages

management:
  tracing:
    enabled : true
    sampling:
      probability: 1.0
  endpoints:
    web:
      base-path: ""
      path-mapping:
        health: health
  health:
    ldap:
      enabled: false
